if(EXISTS "D:/StudyLab/BasicsProg/labwork2-hodzhakhov/tests/number_tests[1]_tests.cmake")
  include("D:/StudyLab/BasicsProg/labwork2-hodzhakhov/tests/number_tests[1]_tests.cmake")
else()
  add_test(number_tests_NOT_BUILT number_tests_NOT_BUILT)
endif()
